### ISSUE TITLE
Choice of state management library

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/my_sarafu#1]
The state management library should be:

- Testable
- Good support for DI (Dependency Injection) and/or separation of logic

Candidates:

- BloC
- Riverpod

**Comment by kamikazechaser** [comment]
Hey @williamluke4 @sanjh @blayziken I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/mobile-app-6316189d08aec4da03692470/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by blayziken** [comment]
I'm inclined towards using BLoC

**Comment by kamikazechaser** [comment]
Finalized on bloc
