### ISSUE TITLE
Upgrade Flutter SDK version

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/my_sarafu#21]
- Current Flutter SDK version is undefined.

**Comment by kamikazechaser** [comment]
Ok, so that SDK is the Dart SDK, the flutter SDK is defined by:

```
flutter: ^3.0.0
```

- https://dart.dev/tools/pub/pubspec#sdk-constraints

**Comment by sanjh** [comment]
this project is created on flutter 3.3.0 .. can you share me the issues .. although i am compiling on android

**Comment by kamikazechaser** [comment]
The only other issue that is Android related is #22. Also from what I know minSdk allowed on PlayStore is either 20 or 22. The default is set to 18. I can also make this change.

**Comment by blayziken** [comment]
min: 22
target: 31

**Comment by kamikazechaser** [comment]
Would there be a benefit of setting the min higher? To say 26?

**Comment by blayziken** [comment]
I don't think so, setting it to 26 would exclude earlier android versions like Lollipop and Marshmallow from getting the app

**Comment by kamikazechaser** [comment]
Ok lets go with 22, 31
